# Generated by Django 5.0.4 on 2024-04-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('security_email1', models.EmailField(max_length=254)),
                ('documents', models.FileField(upload_to='building_documents/%Y/%m/%d')),
            ],
        ),
    ]
