# Generated by Django 5.0.4 on 2024-04-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='security_email2',
            field=models.EmailField(default=456, max_length=254),
            preserve_default=False,
        ),
    ]
