# Generated by Django 5.0.4 on 2024-04-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_building_security_email2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='building_documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='building',
            name='security_email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
