# Generated by Django 5.0.4 on 2024-04-24 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_building_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.building'),
        ),
    ]
