# Generated by Django 5.0.4 on 2024-05-03 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_property_building_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact',
            new_name='customer_contact',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='passport_file',
            new_name='customer_passport_file',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED'), ('ENROUTE', 'ENROUTE'), ('ARRIVED', 'ARRIVED'), ('CLEANING', 'CLEANING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('CHANGED', 'CHANGED')], default='PENDING')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.booking')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_id', models.TextField(null=True)),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('refunded', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.TextField(choices=[('PENDING', 'PENDING'), ('NOT_APPLICABLE', 'NOT_APPLICABLE'), ('PAID', 'PAID'), ('REFUNDED', 'REFUNDED')], default='PENDING')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.booking')),
            ],
        ),
    ]
