# Generated by Django 5.0.4 on 2024-05-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_contact_customer_customer_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_passport_file',
            new_name='passport_file',
        ),
    ]
