# Generated by Django 5.0.4 on 2024-05-07 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_customer_contact_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Building', to='core.building'),
        ),
    ]
